package com.codingcat.commerce.module.response;

import com.querydsl.core.types.Order;
import com.querydsl.core.types.OrderSpecifier;
import com.querydsl.core.types.dsl.PathBuilder;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;

/**
 * 페이징된 데이터를 반환하는 DTO
 */
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PageResponse<T> {

  @Schema(description = "실제 데이터 목록")
  private List<T> data;

  @Schema(description = "페이징 정보")
  private PageInfo page;

  /**
   * 페이징 정보 DTO
   */
  @Getter
  @NoArgsConstructor
  @AllArgsConstructor
  @Builder
  public static class PageInfo {

    @Schema(description = "현재 페이지 (0-based)", example = "0")
    private int currentPage;

    @Schema(description = "페이지 크기", example = "10")
    private int pageSize;

    @Schema(description = "전체 데이터 개수", example = "25")
    private long totalElements;

    @Schema(description = "전체 페이지 수", example = "3")
    private int totalPages;

    /*** Spring Page 객체에서 PageInfo로 변환합니다.*/
    public static PageInfo from(Page<?> page) {
      return PageInfo.builder()
          .currentPage(page.getNumber())
          .pageSize(page.getSize())
          .totalElements(page.getTotalElements())
          .totalPages(page.getTotalPages())
          .build();
    }
  }

  /**
   * Spring Page 객체에서 PageResponse로 변환합니다.
   */
  public static <T> PageResponse<T> from(Page<T> page) {
    return PageResponse.<T>builder()
        .data(page.getContent())
        .page(PageInfo.from(page))
        .build();
  }

  // Pageable에서 정렬 조건 추출
  public static <T> List<OrderSpecifier<?>> getOrderSpecifiers(
    Pageable pageable,
    Class<T> entityClass,
    String variable
  ) {

    PathBuilder<T> entityPath = new PathBuilder<>(entityClass, variable);

    List<OrderSpecifier<?>> orderSpecifiers = new ArrayList<>();

    for (Sort.Order order : pageable.getSort()) {
      Order direction = order.isAscending() ? Order.ASC : Order.DESC;
      orderSpecifiers.add(
        new OrderSpecifier<>(
          direction,
          entityPath.getComparable(
            order.getProperty(),
            Comparable.class
          )
        )
      );
    }

    return orderSpecifiers;
  }
}
/*
예상 응답
{
  "status": "OK",
  "code": "sm.common.success.default",
  "message": "success",
  "content": {
    "data": [
      {
        "ledgerIdx": 1,
        "type": "EXPENSE",
        "amount": 15000,
        "desc": "점심 먹음",
        "place": "스타벅스",
        "category": "FOOD",
        "paymentMethod": "CREDIT_CARD",
        "recordedDate": "2026-02-24",
        "isAutoGenerated": false,
        "createdDateTime": "2026-02-24T10:30:00",
        "modifiedDateTime": "2026-02-24T10:30:00"
      },
      {
        "ledgerIdx": 2,
        "type": "EXPENSE",
        "amount": 25000,
        "desc": "저녁 먹음",
        "place": "한식당",
        "category": "FOOD",
        "paymentMethod": "DEBIT_CARD",
        "recordedDate": "2026-02-23",
        "isAutoGenerated": false,
        "createdDateTime": "2026-02-23T18:00:00",
        "modifiedDateTime": "2026-02-23T18:00:00"
      }
    ],
    "page": {
      "currentPage": 0,
      "pageSize": 10,
      "totalElements": 25,
      "totalPages": 3
    }
  }
}
*/